### ISSUE TITLE
global yarn install can't generate report

### ISSUE THREAD

**Issue by crimson-med** [crimson-med/vestigo#1]
When executing the command from a yarn global install the report template is not found.
Resource files should be packaged properly.

```
Error: ENOENT: no such file or directory, open './templates/report.md'
    at Report.exportSummary (~/.config/yarn/global/node_modules/vestigo/lib/classes/report.js:31:27)
    at Scan.run (~/.config/yarn/global/node_modules/vestigo/lib/commands/scan.js:93:29)
    at async Scan._run (~/.config/yarn/global/node_modules/@oclif/command/lib/command.js:44:20)
    at async Config.runCommand (~/.config/yarn/global/node_modules/@oclif/config/lib/config.js:160:9)
    at async Main.run (~/.config/yarn/global/node_modules/@oclif/command/lib/main.js:21:9)
    at async Main._run (~/.config/yarn/global/node_modules/@oclif/command/lib/command.js:44:20)
```

**Comment by crimson-med** [comment]
- use `os.tempdir()` to save reports 
- add output dir path as well
